//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace salahuddinahmed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int Id { get; set; }
        public string Class { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
        public string Roll { get; set; }
        public string Shift { get; set; }
        public string Nationality { get; set; }
        public string Office_Phone { get; set; }
        public string Title { get; set; }
        public string DateOfBirth { get; set; }
        public string DateOfEmployment { get; set; }
        public string Mobile_Number { get; set; }
        public string Home_address { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public Nullable<bool> Image_Provided { get; set; }
        public Nullable<bool> Form_Filled { get; set; }
        public string Blood_Group { get; set; }
        public Nullable<bool> Blood_Group_Checked { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
